package test.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table COUNTRY
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Country {
    /**
     * ID
     */
    private Short id;

    /**
     * COUNTRYNAME
     */
    private String countryname;

    /**
     * COUNTRYCODE
     */
    private String countrycode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRY.ID
     *
     * @return the value of COUNTRY.ID
     *
     * @mbggenerated
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRY.ID
     *
     * @param id the value for COUNTRY.ID
     *
     * @mbggenerated
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRY.COUNTRYNAME
     *
     * @return the value of COUNTRY.COUNTRYNAME
     *
     * @mbggenerated
     */
    public String getCountryname() {
        return countryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRY.COUNTRYNAME
     *
     * @param countryname the value for COUNTRY.COUNTRYNAME
     *
     * @mbggenerated
     */
    public void setCountryname(String countryname) {
        this.countryname = countryname == null ? null : countryname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRY.COUNTRYCODE
     *
     * @return the value of COUNTRY.COUNTRYCODE
     *
     * @mbggenerated
     */
    public String getCountrycode() {
        return countrycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRY.COUNTRYCODE
     *
     * @param countrycode the value for COUNTRY.COUNTRYCODE
     *
     * @mbggenerated
     */
    public void setCountrycode(String countrycode) {
        this.countrycode = countrycode == null ? null : countrycode.trim();
    }
}